DROP DATABASE IF EXISTS carlyboard;
CREATE DATABASE carlyboard; 
USE carlyboard; 

CREATE TABLE board (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) DEFAULT NULL
);

CREATE TABLE section (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    board_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    FOREIGN KEY fk_section_board(board_id)
    REFERENCES board(ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE stickie (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    section_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY fk_sticky_section(section_id)
    REFERENCES section(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);
